CREATE TABLE IF NOT EXISTS user_settings (
  line_user_id VARCHAR(64) PRIMARY KEY,
  daily_goal_grams INT NOT NULL DEFAULT 100,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS protein_log (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  line_user_id VARCHAR(64) NOT NULL,
  log_date DATE NOT NULL,
  total_grams INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_date (line_user_id, log_date)
);
